---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mariadb.fullname" . }}-pod-{{ (int .Values.slave.replicas) }}
  labels:
    app: "{{ template "mariadb.name" . }}"
    chart: "{{ template "mariadb.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
{{- if .Values.metrics.enabled }}
  annotations:
{{ toYaml .Values.metrics.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "ClusterIP" }}
  {{- if .Values.service.clusterIp }}
  clusterIP: {{ .Values.service.clusterIp }}
  {{- end }}
  {{- end }}
  ports:
  - name: mysql
    port: {{ .Values.service.port }}
    targetPort: mysql
{{- if .Values.metrics.enabled }}
  - name: metrics
    port: 9104
    targetPort: metrics
{{- end }}
  selector:
    app: "{{ template "mariadb.name" . }}"
    release: "{{ .Release.Name }}"
    statefulset.kubernetes.io/pod-name: {{ template "mariadb.fullname" . }}-master-0


{{ $kra := include "mariadb.name" . }}
{{ $fullname := include "mariadb.fullname" . }}
{{ $chart := include "mariadb.chart" . }}
{{ $releasename := .Release.Name | quote }}
{{ $releaseservice := .Release.Service | quote }}
{{ range $i, $e := until (int .Values.slave.replicas) }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-pod-{{ $e }}
  labels:
    app: "{{ $kra }}"
    chart: "{{ $chart }}"
    release: {{ $releasename }}
    heritage: {{ $releaseservice }}
spec:
  type: "ClusterIP"
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: "{{ $kra }}"
    release: {{ $releasename }}
    statefulset.kubernetes.io/pod-name: {{ $fullname }}-slave-{{ $i }}
{{ end }}
