---
###################################
# Headless Orchestrator Service
###################################
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-headless
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: vitess
    component: orchestrator
spec:
  clusterIP: None
  ports:
    - name: web
      port: 80
      targetPort: 3000
  selector:
    component: orchestrator
    app: vitess

