---
###################################
# Master Orchestrator Service
###################################
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  labels:
    app: vitess
    component: orchestrator
spec:
  ports:
    - name: web
      port: 80
      targetPort: 3000
  selector:
    app: vitess
    component: orchestrator
  type: ClusterIP

